### ISSUE TITLE
Install without php-mysqli causes error BEFORE Kalkun does checks

### ISSUE THREAD

**Issue by realJoshByrnes** [kalkun-sms/Kalkun#263]
An uncaught Exception was encountered
Type: Error
Message: Call to undefined function mysqli_init()
Filename: /var/www/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php
Line Number: 135

**Comment by tenzap** [comment]
If you want to test, this should be fixed in my branch https://github.com/tenzap/Kalkun/tree/fix-002-installation-onCodeStyle. Your other issue for "sessions" should be fixed too, but I couldn't test because session is built in my php, so I can't disable it to test.

Your feedback would be welcome.

I'm waiting for my other PR to be merged to create the PR for this.

**Comment by tenzap** [comment]
Please close the issue, this is fixed in https://github.com/kalkun-sms/Kalkun.

Kalkun is now being maintained at a new home. Please head over to https://github.com/kalkun-sms/Kalkun for the latest version.
